sudo: required

language: generic

services:
  - docker

env:
  - COMMAND='make test CI=true'
  - COMMAND='make lint'

install:
  - docker build --tag=etheroll-js .

script:
  - docker run etheroll-js /bin/sh -c "$COMMAND"
