version: '3.5'
services:
  hdfs:
    container_name: etheroll
    image: etheroll-js
    build:
      context: .
    command: |
      /bin/bash -c "
        set -e
        make start
        /bin/bash || exit 0
      "
    ports:
    - "3000:3000"
    - "80:3000"
    working_dir: /app
